
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDAND ATOM LPAREN OR RPAREN SEQsequent : expression SEQ expressionexpression : ATOMexpression : expression AND expressionexpression : expression OR expressionexpression : LPAREN expression RPAREN'
    
_lr_action_items = {'ATOM':([0,4,5,6,7,],[3,3,3,3,3,]),'LPAREN':([0,4,5,6,7,],[4,4,4,4,4,]),'$end':([1,3,9,10,11,12,],[0,-2,-1,-3,-4,-5,]),'SEQ':([2,3,10,11,12,],[5,-2,-3,-4,-5,]),'AND':([2,3,8,9,10,11,12,],[6,-2,6,6,-3,6,-5,]),'OR':([2,3,8,9,10,11,12,],[7,-2,7,7,-3,-4,-5,]),'RPAREN':([3,8,10,11,12,],[-2,12,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sequent':([0,],[1,]),'expression':([0,4,5,6,7,],[2,8,9,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sequent","S'",1,None,None,None),
  ('sequent -> expression SEQ expression','sequent',3,'p_sequent','ll_run.py',56),
  ('expression -> ATOM','expression',1,'p_expression_atom','ll_run.py',60),
  ('expression -> expression AND expression','expression',3,'p_expression_and','ll_run.py',64),
  ('expression -> expression OR expression','expression',3,'p_expression_or','ll_run.py',68),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','ll_run.py',72),
]
